### ISSUE TITLE
PHP HereDoc Support

### ISSUE THREAD

**Issue by sumityadav** [dericofilho/sublime-phpfmt#146] opened 2015-06-20 17:45 UTC
Do you support PHP HEREDOC/NOWDOC?

Currently it aligns the HEREDOC which breaks the code.

**Comment by dericofilho** [comment] 2015-06-20 17:48
@sumityadav hi I am really sorry for this bug. Please, send me a piece of code which reproduces the undesired behavior and the plugin configuration. I am going to fix it ASAP.

**Comment by felonious** [comment] 2015-06-21 12:40
my mac with osx el capitan comes with PHP 5.5.24 (cli) (built: May 12 13:48:59 2015), and will not install another version as I disable the message to update the php.

**Comment by dericofilho** [comment] 2015-06-21 12:41
@felonius is this related to this particular bug?

**Comment by felonious** [comment] 2015-06-21 12:44
yes, already found a solution, I will remove the phpfmt install the plugin phpcs

**Comment by dericofilho** [comment] 2015-06-21 12:44
@felonious ok!

**Comment by dericofilho** [comment] 2015-06-21 13:29
I just realized that @felonious is not @sumityadav.

@sumityadav again, I am really sorry for this bug. Please, send me a piece of code which reproduces the undesired behavior and the plugin configuration. I am going to fix it ASAP.

**Comment by sumityadav** [comment] 2015-06-21 19:34
Sorry for the delayed response. Here is the snippet of the code that doesn't work. Copy/paste it in Sublime Text 3 and try to save it. It will indent the input which will break the code. 


```php
<?php

if (true):
    if (true):
        echo "Testing HereDoc";
    endif;

    $html_out = <<<HtmlOutput
	<div>Some text</div>
HtmlOutput;
endif;
```

Config
```json
{
	"format_on_save": true,
	"passes":
	[
	],
	"php55warning": true,
	"psr2": true,
	"version": 3
}
```

**Comment by dericofilho** [comment] 2015-06-21 19:36
@sumityadav I managed to reproduce the bug. I am going to fix it ASAP.

**Comment by sumityadav** [comment] 2015-06-21 19:37
Woah!! What speed.. Thanks for the lightning response.

**Comment by dericofilho** [comment] 2015-06-21 19:48
@sumityadav please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/b31230e677328bdd262c9d25f8456106dd76235a and try again.

**Comment by sumityadav** [comment] 2015-06-22 10:48
@dericofilho I am not able to test it because of the minimum php requirement of 5.6.

I am using [phpbrew](https://github.com/phpbrew/phpbrew) and both cli and browser shows 5.6.6 but the plugin still detects system installed php (default: 5.5.20 in Yosemite)

```
$ php -v
PHP 5.6.6 (cli) (built: Mar  7 2015 23:29:59)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by dericofilho** [comment] 2015-06-22 10:49
@sumityadav In configuration file, be sure to update `php_bin` which the address for php 5.6

On command line, type `which php`, copy&paste the address into configuration file.

**Comment by sumityadav** [comment] 2015-06-22 12:04
Sorry to bother you but it doesn't seem to work even after setting the php_bin in the configuration. 
```
phpfmt (php_ver) cmd:
 ['/Users/sumityadav/.phpbrew/php/php-5.6.6/bin/php', '-v']
phpfmt (php_ver) out:
 PHP 5.6.6 (cli) (built: Mar  7 2015 23:29:59) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans

phpfmt (php_ver) err:
 
error: Null inputs. (diff_main)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "phpcs in /Users/sumityadav/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 476, in run
  File "phpcs in /Users/sumityadav/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 143, in get_errors
  File "phpcs in /Users/sumityadav/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 219, in execute
  File "phpcs in /Users/sumityadav/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 222, in parse_report
  File "phpcs in /Users/sumityadav/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 173, in shell_out
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'phpcs'
```

PHPCS is also present which was installed by `composer global require "squizlabs/php_codesniffer=*"`.

```
$ phpcs heredoc.php

FILE: /Users/skumar/Sites/sandbox/heredoc.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 2 | ERROR | [ ] Missing file doc comment
 3 | ERROR | [x] There must be a single space between the closing
   |       |     parenthesis and the opening brace of a multi-line IF
   |       |     statement; found 0 spaces
 4 | ERROR | [x] There must be a single space between the closing
   |       |     parenthesis and the opening brace of a multi-line IF
   |       |     statement; found 0 spaces
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 19ms; Memory: 3.5Mb
```

**Comment by dericofilho** [comment] 2015-06-22 12:09
@sumityadav phpfmt and phpcs are different packages. From what I see in your error, you should be asking for help to benmatselby/sublime-phpcs

**Comment by sumityadav** [comment] 2015-06-22 12:13
Do you know why phpfmt doesn't work and error out?

```
phpfmt (php_ver) err:
```

**Comment by sumityadav** [comment] 2015-06-22 12:56
@dericofilho I have fixed the issues with phpcs by setting up the executable paths and it seem to work now, but phpfmt still gives the error:

```
phpfmt (php_ver) cmd:
 ['/Users/sumityadav/.phpbrew/php/php-5.6.6/bin/php', '-v']
phpfmt (php_ver) out:
 PHP 5.6.6 (cli) (built: Mar  7 2015 23:29:59) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans

phpfmt (php_ver) err:
 
```

**Comment by dericofilho** [comment] 2015-06-22 13:27
@sumityadav `phpfmt (php_ver) err:` is empty because there was no error.

Please, try to disable the plugins and test them individually. I am ready to solve any incompatibility with PHPCS. But we need first to isolate them.

**Comment by sumityadav** [comment] 2015-06-22 14:19
If `phpfmt (php_ver) err:` being empty is intentional, then I think the fix you made for heredoc is working.

**Comment by dericofilho** [comment] 2015-06-22 14:20
@sumityadav Nice. May I close this issue?

**Comment by sumityadav** [comment] 2015-06-22 14:24
It doesn't break the code but it still aligns the code between the heredoc. 

Do you think we should format the code within that block?

Did you make a release and will autoupdate?

**Comment by dericofilho** [comment] 2015-06-22 14:25
>It doesn't break the code but it still aligns the code between the heredoc.
>Do you think we should format the code within that block?

what do you mean by that? can you provide me an example?

I made a release, yes, to deprecated the support for PHP 5.5 and put this change in.

**Comment by sumityadav** [comment] 2015-06-22 14:33
Use the same code I gave and try to save multiple times. It will move the div tag every time you save.

```php
<?php

if (true):
    if (true):
        echo "Testing HereDoc";
    endif;

    $html_out = <<<HtmlOutput
    <div>Some text</div>
HtmlOutput;
endif;
```

**Comment by dericofilho** [comment] 2015-06-22 14:33
@sumityadav OK, I am going to fix it ASAP.

**Comment by dericofilho** [comment] 2015-06-22 14:50
please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.1.1

**Comment by sumityadav** [comment] 2015-06-22 15:18
Fixed, Thanks :)

**Closed** 2015-06-22 15:18 UTC
Labels: bug, waiting feedback
