### ISSUE TITLE
use statement gets lost when formatting

### ISSUE THREAD

**Issue by vith** [dericofilho/sublime-phpfmt#112] opened 2015-04-06 23:26 UTC
I was unable to reproduce this via the command line tool directly or strip down the test case much further. The use statement for class `GETS_LOST` goes missing when formatting is run.

# Version
`sublime-phpfmt v2.15.0`

# Config
```python
{
	"psr2": true
}
```

# Input
```php
<?php

namespace Somewhere;

use A\BaseClass;
use A\IA;
use A\II;
use A\Output\OutputInterface;
use Z\Alpha\Ssss;
use A\Yowza;
use A\Config\Definition\GETS_LOST;
use Z\SillyThing;

class MyClass extends BaseClass
{
    protected function snap()
    {
        $this
            ->method(
                IA::CONSTANT,
                'string that must be here'
            )
            ->method(Different::CONSTANT)
        ;
    }

    protected function crackle(II $input, OutputInterface $output)
    {
        $name = 'ok';
        $longerName = 'no';
    }

    private function pop(Ssss $site)
    {
        $foo           = [Yowza::method()];
        $thinger       = new GETS_LOST;
        $loooooooooong = $thinger->doThing(new SillyThing);
    }
}
```

# Output
```php
<?php

namespace Somewhere;

use A\BaseClass;
use A\IA;
use A\II;
use A\Output\OutputInterface;
use A\Yowza;
use Z\Alpha\Ssss;
use Z\SillyThing;

class MyClass extends BaseClass
{
    protected function snap()
    {
        $this
            ->method(
                IA::CONSTANT,
                'string that must be here'
            )
            ->method(Different::CONSTANT)
        ;
    }

    protected function crackle(II $input, OutputInterface $output)
    {
        $name = 'ok';
        $longerName = 'no';
    }

    private function pop(Ssss $site)
    {
        $foo = [Yowza::method()];
        $thinger = new GETS_LOST;
        $loooooooooong = $thinger->doThing(new SillyThing);
    }
}
```

**Comment by dericofilho** [comment] 2015-04-06 23:27
@vith I am sorry for this bug. I shall fix it ASAP.

**Comment by dericofilho** [comment] 2015-04-06 23:29
@vith I could not reproduce this bug. Please, add `"debug":true` to your configuration file and paste here the output from console.

**Comment by vith** [comment] 2015-04-06 23:31
```
phpfmt (php version) out:
 PHP 5.6.7 (cli) (built: Mar 27 2015 16:53:18) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

phpfmt (php version) err:
 
cmd_fmt:  ['php', '/home/vith/.config/sublime-text-3/Packages/phpfmt/fmt.phar', '--config=/home/vith/.config/sublime-text-3/Packages/phpfmt/php.tools.ini', '--psr2', '--smart_linebreak_after_curly', '-v', '-o=-', '-']
p:
 0
err:
 Used passes: RTrim, EliminateDuplicatedEmptyLines, LeftAlignComment, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2CurlyOpenNextLine, PSR2LnAfterNamespace, PSR2IndentWithSpace, PSR2KeywordsLowerCase, Reindent, ReindentAndAlignObjOps, ReindentIfColonBlocks, ReindentLoopColonBlocks, ReindentColonBlocks, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine
```

`/home/vith/.config/sublime-text-3/Packages/phpfmt/php.tools.ini` is an empty file.

**Comment by dericofilho** [comment] 2015-04-06 23:35
@vith With the proposed code, I cannot reproduce the bug.

**Comment by vith** [comment] 2015-04-06 23:39
If I run `php /home/vith/.config/sublime-text-3/Packages/phpfmt/fmt.phar --config=/home/vith/.config/sublime-text-3/Packages/phpfmt/php.tools.ini --psr2 --smart_linebreak_after_curly -v -o=- -` on the command line, paste in the input and press `^d`, I also cannot reproduce the bug. Perhaps it's an issue on the python side with the sublime package?

I will try a clean sublime profile, but it has occurred on both my work computer and home computer, both running Arch Linux.

**Comment by dericofilho** [comment] 2015-04-06 23:40
@vith Even on ST3 here, I cannot reproduce the bug.

**Comment by vith** [comment] 2015-04-06 23:44
It does occur for me on a clean sublime config with only Package Control and sublime-phpfmt installed on Arch Linux. I will try on a Ubuntu virtual machine.

**Comment by dericofilho** [comment] 2015-04-06 23:45
@vith Be careful with typos. fmt.phar will always remove unused imports - and usually when such bug happens, it is some sort of typo.

**Comment by vith** [comment] 2015-04-06 23:56
I am able to reproduce it in the Ubuntu 14.10 64bit live environment.
```shell
sudo apt update
sudo apt install php5-cli
wget http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3083_amd64.deb
sudo dpkg -i sublime-text_build-3083_amd64.deb
```

Then package control, sublime-phpfmt, phpfmt.sublime-settings, and the input copied and pasted directly from this issue.

**Comment by vith** [comment] 2015-04-06 23:56
Which OS are you not seeing it happen on?

**Comment by dericofilho** [comment] 2015-04-06 23:57
@vith Worked fine both with MacOS X and Windows.

**Comment by dericofilho** [comment] 2015-04-06 23:59
@vith I am going to test on Ubuntu now.

**Comment by dericofilho** [comment] 2015-04-07 00:05
@vith I just managed to reproduce the bug with a different configuration on Windows.

**Comment by vith** [comment] 2015-04-07 00:09
I just tried xubuntu-14.04.2-desktop-amd64 and it did **not** occur there.

**Comment by dericofilho** [comment] 2015-04-07 00:15
@vith This is a bug at https://code.google.com/p/google-diff-match-patch/ and there is not a lot I can do to fix it. I will file a bug on this project and hope they fix it. Meanwhile, I shall try to look for an alternative library. Internally, php.tools is generating the correct output.

**Comment by dericofilho** [comment] 2015-04-07 00:17
@vith I tried to reproduce the bug on ST2, and ST2 is working just fine - so it really seems something wrong with ST3's Python. I will rule out as a bug from google-diff-match-patch library - it consistently works even when I take the correct steps to reproduce the error.

**Comment by dericofilho** [comment] 2015-04-07 00:38
@vith please, update to https://github.com/dericofilho/sublime-phpfmt/commit/4643603c713ecf675237051b891fba25cafb44a5

**Comment by vith** [comment] 2015-04-07 00:42
I added `print("res:\n", res.decode('utf-8'))` to https://github.com/dericofilho/sublime-phpfmt/blob/master/phpfmt.py#L355 and can see that it's not caused by data lost in the pipe between php and python.

Updating to that commit to test.

**Comment by vith** [comment] 2015-04-07 00:47
Looks like 4643603 fixed it for me.

**Comment by dericofilho** [comment] 2015-04-07 00:48
@vith I will make a release of it ASAP. Closing the issue now. If it happens again, please reopen it.

**Closed by dericofilho** 2015-04-07 00:48 UTC
Labels: bug, waiting feedback
